"""Add suggested_pii_type

Revision ID: 042880bea09c
Revises: b2c3d4e5f6a7
Create Date: 2026-04-20 13:36:30.222918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042880bea09c'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('suggested_pii_type', sa.String(), nullable=True))
    op.drop_constraint(op.f('token_vault_token_key'), 'token_vault', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('token_vault_token_key'), 'token_vault', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('columns', 'suggested_pii_type')
    # ### end Alembic commands ###
