"""describe change

Revision ID: 5322e905a7cd
Revises: 042880bea09c
Create Date: 2026-04-29 11:01:16.988997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5322e905a7cd'
down_revision: Union[str, None] = '042880bea09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_rules', sa.Column('database_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_rules', 'database_name')
    # ### end Alembic commands ###
